### ISSUE TITLE
The import @lit-protocol/lit-node-client doesn't work in Sveltekit. If you try to import this library in a Sveltekit project, the app throws a 500 error with ReferenceError: global/process is not defined

### ISSUE THREAD

**Issue by ChristianOConnor** [LIT-Protocol/js-sdk#141]
https://github.com/ChristianOConnor/lit-v2-svelte-integrate this is a demo app that demonstrates my problem.

I explained the problem in the readme:
Click "Lit Test" in the header and you will be directed to "Lit" where you'll get a 500 error. If you open the browser console (in either Firefox or Google Chrome), you will see "ReferenceError: global is not defined" as well as "Uncaught (in promise) ReferenceError: process is not defined."

**Comment by Ansonhkg** [comment]
hi @ChristianOConnor 

Thanks for providing the demo app; that allowed me to quickly to check the problem!

The error occurs I believe is because Svelte doesn't apply automatic polyfills, unlike react, nextjs . These latter frameworks use bundlers like webpack,which automatically polyfill these variables to make the code work in the browser.

For now, you'll need to manually polyfill it in your vite.config.ts file. I've added this issue to our to-do list and hopefully, we'll have it fixed in upcoming patches.


```js
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()],
	define: {
		'process.env.NODE_DEBUG': 'false',
		'window.global': 'globalThis'
	}
});

```

**Comment by ChristianOConnor** [comment]
Perfect! This worked thanks!
